name: Build fonts

on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Make release
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:latest
    steps:
      - name: Update packages
        run: |
          pacman -Syyu --noconfirm
      - name: Install dependencies
        run: |
          pacman -S --noconfirm base git tar which zip libffi jre17-openjdk wget
      - name: Install python
        run: |
          pacman -S --noconfirm python python-pipenv python-setuptools
      - name: Install fontforge
        run: pacman -S --noconfirm fontforge
      - uses: actions/checkout@v2
      - name: Build fonts
        run: |
          pipenv --python /bin/python install; pipenv run python build.py fonts
      - name: Save version
        id: version
        run: |
          echo "version=${GITHUB_REF#refs/tags/}" | tr . - >> $GITHUB_OUTPUT
      - name: Zip fonts
        run: |
          mv build CozetteFonts; cp ./LICENSE CozetteFonts/LICENSE; zip -r CozetteFonts-${{ steps.version.outputs.version }}.zip CozetteFonts
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "CozetteFonts-${{ steps.version.outputs.version }}.zip,CozetteFonts/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          body: "See [CHANGELOG.md](https://github.com/slavfox/Cozette/blob/master/CHANGELOG.md)"
